### ISSUE TITLE
怎么处理文字紧接着前面的文字滚动，两次滚动之间不留空白呢

### ISSUE THREAD

**Issue by kongmj** [cheng-kang/react-native-lahk-marquee-label#5]
怎么处理文字紧接着前面的文字滚动，两次滚动之间不留空白呢，不是现在要第一次文字全部滚完，才开始第二轮滚动？

**Comment by cheng-kang** [comment]
不好意思，这个组件设计的适用场景就是“循环滚动，前一轮消失再出现后一轮”。暂时不会支持你提到的这种情况。
